name: hello world
on:
  push:
    branches: [unittest]
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:

    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - run: pip install unittest

    - run: python main_test.py